<?php

return [

    '1'       => 'TERMS OF USE',
    '2'       => 'Access to and use of this website is subject to the following provisions. If you do not agree with this, please refrain from usage of this website. This site was developed and is administrated by the Global Services Management AG (hereinafter GSM). We reserve the right at any time without notice to change our website, the general terms and conditions at our discretion, in whole or in part, and / or discontinue the website. We therefore ask you to look through this website again on your next visit and note any changes / additions to content or information.',
    '3'       => 'SURRENDER OF USE',
    '4'       => 'All information published on this website, including documents and presentations, are the sole property of GSM. Permission to use the aforementioned is granted on the proviso that the relevant copyright note is displayed on all copies, that such use of the information is used only for personal purposes and not for commercial purposes, the information is not modified in any way, and that all illustrations on the website can be used only in conjunction with the accompanying text.',
    '5'       => 'TRADEMARKS AND COPYRIGHTS',
    '6'       => 'All trademarks on this website are the property of GSM, unless they are identified as third-party rights or in any other way perceivable as such. Any unauthorized use of these trademarks or other materials is expressly prohibited and constitutes a violation of copyright, trademark, or other intellectual property rights.',
    '7'       => 'LIMITATION OF LIABILITY',
    '8'       => 'GSM has gained the information shown on this website from internal and external sources to the best of our knowledge, using professional diligence. We strive to expand this information and keep it as current as possible. The information on this website are only the representation of GSM and its products and services. However, we make no warranty—either express or implied—as to the ‘completeness’ or accuracy of the information on this site. In particular, you should be aware that this information may no longer be current. For this reason, you should not disclose information you obtain from this website. Advice given on this website does not exempt you from conducting your own checks on our latest information / advice. Users of this website declare that they agree to access the site and its content at their own risk. Neither GSM nor the parties involved in the creation, production, or hosting of this site are liable for any damage or injury, resulting from access or the impossibility of access, use or inability to use this website, or from the fact that you rely on any information contained on this website. The information on this website (www.gsmanagement.ch) does not constitute an offer to sell, nor the solicitation of an offer to buy or subscribe for shares, but for informational purposes only.',
    '9'       => 'INFORMATION PROVIDED BY YOU',
    '10'       => 'The user of this website is fully responsible for all information that he/she sends to GSM, the content, and its accuracy. They are also responsible for ensuring that the rights of third parties are not infringed. The user agrees that GSM may store this information and use it for statistical analysis, or for any other specified business purpose—unless the information involves personal details—going beyond master data or usage data. GSM is especially authorized to use the contents of such information: including ideas, inventions, concepts, techniques or know-how contained therein, for any purpose, including developing, manufacturing, and / or marketing of products or services, and to reproduce such information and make it available unreservedly to third parties.',
    '11'       => 'INTERNATIONAL USERS',
    '12'       => 'This website is checked, operated and updated by GSM in Zurich (Switzerland). GSM does not guarantee that the information presented on this website and in places outside of Switzerland are correct, in particular, that products and services are available in the same format, size, and at the same conditions. If you access this site from a location outside of Switzerland and view / download its content, you are responsible for ensuring that this is consistent with the applicable local laws in your location. Applicable Law Any in connection with the site or its use legal claims or actions shall be governed exclusively by the laws of Switzerland.',
    '13'       => 'FORWARD-LOOKING STATEMENTS',
    '14'       => 'This website contains forward-looking statements. These statements use words such as “believes,” “expects,” “anticipates,” “future” or “expects”, or similar examples. Various known and unknown risks, uncertainties, and other factors could cause the actual results, financial situations, and the development or performance of the company to differ materially from those that may be expressed or implied by such forward-looking statements.',
    '15'       => 'These factors include, among others:',
    '16'       => '• Economic downturns in the industries in which its business activities are operated<br>• New or amended regulations that increase operating costs or otherwise reduce profitability<br>• Liabilities, especially those associated with environmental laws or product liability claims<br>• Exchange rate fluctuations, and changes in general economic conditions, and other factors identified on this internet site.',
    '17'       => 'These factors include those discussed in our public reports. Against the background of these uncertainties, we caution readers not to place undue reliance on these forward-looking statements. We assume no obligation to update such forward-looking statements or to alter them to conform to future events or developments.',
];
