<?php

return [

    '1'       => 'RECHTLICHES',
    '2'       => 'Zugang zu und Nutzung dieser Website unterliegen den folgenden Bestimmungen. Falls Sie mit diesen nicht einverstanden sind, benutzen Sie diese Website bitte nicht. Diese Website wurde von der Global Services Management AG (im folgenden GSM) entwickelt und wird von ihr administriert. Wir behalten uns das Recht vor, unsere Website, die allgemeinen Nutzungsbedingungen, unsere allgemeinen Geschäftsbedingungen nach eigenem Ermessen jederzeit ohne Ankündigung ganz oder teilweise zu ändern und/oder deren Betrieb einzustellen. Wir bitten Sie daher, bei Ihrem nächsten Besuch dieser Website diese erneut durchzusehen und Änderungen/Ergänzungen zur Kenntnis zu nehmen.',
    '3'       => 'NUTZUNGSÜBERLASSUNG',
    '4'       => 'Sämtliche in dieser Website veröffentlichten Informationen, Dokumente und Darstellungen sind alleiniges Eigentum von der GSM. Die Erlaubnis zu ihrer Verwendung steht unter dem Vorbehalt, dass der Copyrightvermerk auf allen Kopien erscheint, der Gebrauch der Informationen nur persönlichen Zwecken dient und keine kommerzielle Verwertung erfolgt, die Informationen in keiner Weise verändert werden und sämtliche Darstellungen der Website nur zusammen mit dem dazugehörigen Text verwendet werden.',
    '5'       => 'MARKEN UND URHEBERRECHTE',
    '6'       => 'Alle auf dieser Webseite genannten Marken sind Eigentum der GSM, es sei denn, sie sind als Rechte Dritter kenntlich gemacht oder in sonstiger Weise als solche erkennbar. Die nicht autorisierte Nutzung dieser Marken oder sonstiger Materialien ist ausdrücklich verboten und stellt eine Verletzung der Urheberrechte, Markenrechte oder sonstiger Schutzrechte dar.',
    '7'       => 'HAFTUNGSBESCHRÄNKUNG',
    '8'       => 'GSM hat die Informationen, die Sie auf dieser Website vorfinden, aus internen und externen Quellen nach bestem Wissen und Gewissen mit professioneller Sorgfalt zusammengestellt. Wir bemühen uns, dieses Informationsangebot stetig zu erweitern und zu aktualisieren. Die Informationen auf dieser Website dienen nur der Darstellung von der GSM und Ihrer Produkte und Services. Wir übernehmen jedoch keine Garantie – weder ausdrücklich noch stillschweigend – für die Vollständigkeit oder Richtigkeit der Informationen auf dieser Website. Insbesondere sollten Sie sich darüber bewusst sein, dass diese Informationen nicht mehr aktuell sein können. Aus diesem Grund sollten Sie Informationen, die Sie auf dieser Website erhalten, überprüfen, bevor Sie diese – in welcher Art auch immer – verwenden. Die Beratung auf dieser Website befreit Sie nicht von einer eigenen Prüfung unserer aktuellen Beratungshinweise. Die Nutzer dieser Website erklären sich damit einverstanden, auf diese Website und deren Inhalte auf eigenes Risiko zuzugreifen. Weder GSM noch Dritte, die in die Erstellung, Produktion oder Übermittlung dieser Website involviert sind, sind haftbar für Schäden oder Verletzungen, die sich aus dem Zugang oder der Unmöglichkeit des Zugangs, der Nutzung oder Unmöglichkeit der Nutzung dieser Website oder aus dem Umstand, dass Sie sich auf eine Information, die auf dieser Website enthalten ist, verlassen, entstehen. Die Informationen auf dieser Website (www.gsmanagement.ch) stellen kein Angebot zum Verkauf und keine Aufforderung zur Abgabe eines Angebotes zum Kauf oder zur Zeichnung von Aktien dar, sondern dienen ausschließlich Informationszwecken.',
    '9'       => 'VON IHNEN BEREITGESTELLTE INFORMATIONEN',
    '10'       => 'Der Nutzer der Website ist in vollem Umfang für alle Informationen, die er an die GSM sendet, hinsichtlich Inhalt und Richtigkeit verantwortlich. Ebenfalls ist er verantwortlich, dass die Rechte Dritter nicht verletzt werden. Der Nutzer ist damit einverstanden, dass die GSM AG diese Informationen speichert und für statistische Auswertungen oder andere benannte, geschäftliche Zwecke verwendet, sofern es sich nicht um personenbezogene Daten handelt, die über Bestandsdaten oder Nutzungsdaten hinausgehen. Die GSM ist insbesondere befugt, den Inhalt solcher Mitteilungen, einschließlich Ideen, Erfindungen, Konzepte, Techniken oder Know-Hows, das darin enthalten ist, für jeden Zweck zu nutzen, einschließlich der Entwicklung, Herstellung und/oder Vermarktung von Produkten oder Services, und diese Information zu reproduzieren und uneingeschränkt dritten Parteien zugänglich zu machen.',
    '11'       => 'INTERNATIONALE NUTZER',
    '12'       => 'Diese Website wird kontrolliert, betrieben und gepflegt durch die GSM am Standort Zürich (Schweiz). Die GSM übernimmt keine Garantie, dass die auf dieser Website präsentierten Informationen auch in Orten außerhalb von der Schweiz korrekt sind, insbesondere die Produkte und Services in gleicher Aufmachung, Größe und zu gleichen Konditionen verfügbar sind. Sollten Sie diese Website von einem Ort außerhalb von der Schweiz aufrufen und/oder Inhalte herunter laden, so sind Sie selbst dafür verantwortlich, dass dies mit den in Ihrem Aufenthaltsort geltenden lokalen Gesetzen vereinbar ist. Anwendbares Recht Jegliche in Verbindung mit der Website oder deren Benutzung auftretenden Rechtsansprüche oder Prozesse unterliegen ausschließlich den Gesetzen der Schweiz.',
    '13'       => 'ZUKUNFTSGERICHTETE AUSSAGEN',
    '14'       => 'Diese Internetseite enthält bestimmte in die Zukunft gerichtete Aussagen. Diese Angaben werden durch Wörter wie “glaubt”, “geht davon aus”, „voraussichtlich“, „zukünftig“ oder “erwartet” bzw. durch ähnliche Formulierungen gekennzeichnet. Verschiedene bekannte wie auch unbekannte Risiken, Ungewissheiten und andere Faktoren könnten dazu führen, dass die tatsächlichen Ergebnisse, die Finanzlage, die Entwicklung oder die Performance der Gesellschaften wesentlich von denjenigen abweichen, die in diesen in die Zukunft gerichteten Aussagen ausdrücklich oder implizit angenommen werden.',
    '15'       => 'ZU DIESEN FAKTOREN GEHÖREN UNTER ANDEREM:',
    '16'       => '• Konjunkturrückgänge in den Branchen, in denen die Geschäftstätigkeiten betrieben werden<br>• Neue bzw. geänderte Vorschriften, die die Betriebskosten erhöhen oder anderweitig die Profitabilität verringern<br>• Haftung, vor allem im Zusammenhang mit Umweltgesetzen und aus Produkthaftungsansprüchen<br>• Wechselkursschwankungen sowie Änderungen der allgemeinen Wirtschaftslage, sowie sonstige in dieser Internetseite genannte Faktoren.',
    '17'       => 'Diese Faktoren schließen diejenigen ein, die wir in Berichten beschrieben haben. Vor dem Hintergrund dieser Ungewissheiten raten wir dem Leser davon ab, sich zu sehr auf derartige in die Zukunft gerichtete Aussagen zu verlassen. Wir übernehmen keinerlei Verpflichtung, solche zukunftsgerichteten Aussagen fortzuschreiben oder an zukünftige Ereignisse oder Entwicklungen anzupassen.',
];
